import com.google.firebase.database.DatabaseReference;

import java.util.HashMap;
import java.util.Map;

/*
    This class will create a new game on invitation. This creates a new game under games with a unique ID generated by Firebase.
    The game invitation will then be added to the other user's game invitations list.
 */
public class GameMaker extends FireEater {

    @Override
    public CWHResponse handle(CWHRequest request) {
        DatabaseReference ref = FireEater.getDatabase().getReference();
        String UID = request.getExtras().get("uid");
        String invitee = request.getExtras().get("friend");
        String inviteeUID = request.getExtras().get("frienduid");

        DatabaseReference inviteeRef = ref.child("users").child(inviteeUID);

        // Creates new game in games list
        DatabaseReference newGame = ref.child("games").push();
        String gameID = newGame.getKey();

        // Adds the game invitation to the invetee's list
        inviteeRef = inviteeRef.child("game_invitations");
        Map<String, Object > addGameInv = new HashMap<>();
        addGameInv.put(gameID, "feature to be added");
        inviteeRef.updateChildrenAsync(addGameInv);

        // Adds the game object to the game lists
        Game g = new Game(UID);
        newGame.setValueAsync(g);
        if(g.black == null)
        {
            g.black = invitee;
            return new CWHResponse("Invitation sent, starting as black", true);
        }
        else
        {
            g.white = invitee;
            return new CWHResponse("Invitation sent, starting as white", true);
        }
    }
}
